"""
SQLModel Task - Database model for todo items.

This module defines the Task model using SQLModel (hybrid of Pydantic + SQLAlchemy)
for database operations with PostgreSQL/Neon DB.

Example:
    Creating a task:
        >>> from sqlmodel import Session
        >>> from backend.core.config import engine
        >>> task = Task(title="Buy groceries", description="For Sunday dinner")
        >>> with Session(engine) as session:
        ...     session.add(task)
        ...     session.commit()
        ...     session.refresh(task)
        ...     print(task.id)
"""

from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class Task(SQLModel, table=True):
    """
    SQLModel for Task database entity.

    Represents a single todo item with title, description, status, and timestamps.
    This model is used both as an ORM model for database operations and as a
    Pydantic model for request/response validation.

    Attributes:
        id (int): Unique identifier. Auto-generated by database.
        title (str): Task title (required, 1-200 characters).
        description (str): Task description (optional, max 1000 characters).
        status (str): Task status - "pending" or "complete" (default: "pending").
        created_at (datetime): Timestamp when task was created (auto-set).
        completed_at (Optional[datetime]): Timestamp when task was marked complete (None if pending).

    Example:
        >>> task = Task(
        ...     title="Buy groceries",
        ...     description="For Sunday dinner",
        ...     status="pending"
        ... )
        >>> task.title
        'Buy groceries'
        >>> task.status
        'pending'
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    title: str = Field(min_length=1, max_length=200, index=True)
    description: str = Field(default="", max_length=1000)
    status: str = Field(default="pending", index=True)  # "pending" or "complete"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = Field(default=None)

    class Config:
        """SQLModel configuration."""
        from_attributes = True  # Allow creating from dict-like objects

    def mark_complete(self) -> None:
        """
        Mark the task as complete and record completion timestamp.

        Sets status to "complete" and records current UTC datetime.

        Example:
            >>> task = Task(title="Buy groceries")
            >>> task.mark_complete()
            >>> task.status
            'complete'
            >>> task.completed_at is not None
            True
        """
        self.status = "complete"
        self.completed_at = datetime.utcnow()

    def mark_incomplete(self) -> None:
        """
        Mark the task as incomplete and clear completion timestamp.

        Sets status to "pending" and clears completed_at.

        Example:
            >>> task = Task(title="Buy groceries")
            >>> task.mark_complete()
            >>> task.mark_incomplete()
            >>> task.status
            'pending'
            >>> task.completed_at is None
            True
        """
        self.status = "pending"
        self.completed_at = None

    def is_complete(self) -> bool:
        """
        Check if task is marked as complete.

        Returns:
            bool: True if status is "complete", False otherwise.

        Example:
            >>> task = Task(title="Task")
            >>> task.is_complete()
            False
            >>> task.mark_complete()
            >>> task.is_complete()
            True
        """
        return self.status == "complete"

    def is_pending(self) -> bool:
        """
        Check if task is marked as pending.

        Returns:
            bool: True if status is "pending", False otherwise.

        Example:
            >>> task = Task(title="Task")
            >>> task.is_pending()
            True
        """
        return self.status == "pending"

    def __str__(self) -> str:
        """
        Return a human-readable string representation.

        Returns:
            str: Format "[#id] title (status) - Created: timestamp"

        Example:
            >>> task = Task(title="Buy groceries")
            >>> task.id = 1
            >>> str(task)  # doctest: +ELLIPSIS
            '[#1] Buy groceries (pending) - Created: ...'
        """
        created_str = self.created_at.strftime("%Y-%m-%d %H:%M:%S")
        result = f"[#{self.id}] {self.title} ({self.status}) - Created: {created_str}"

        if self.is_complete() and self.completed_at:
            completed_str = self.completed_at.strftime("%Y-%m-%d %H:%M:%S")
            result += f" - Completed: {completed_str}"

        return result

    def __repr__(self) -> str:
        """
        Return debug representation.

        Returns:
            str: Format "Task(id=..., title=..., status=...)"

        Example:
            >>> task = Task(title="Buy groceries")
            >>> task.id = 1
            >>> repr(task)
            "Task(id=1, title='Buy groceries', status='pending')"
        """
        return f"Task(id={self.id}, title={self.title!r}, status={self.status!r})"
